version: '3'
services:
  web:
    build: ./web
  redis:
    image: "redis:alpine"
  nginx:
    ports:
     - "5000:80"
    volumes:
      - ./nginx/nginx.default.conf:/etc/nginx/conf.d/default.conf
    image: nginx:alpine
    # build: ./nginx
    